pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/exceptions/BadRequestException.java
pcss-common-application/src/main/resources/application-test.yml
pcss-common-application/src/main/resources/application.yml
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java

change reporting endpoint

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-2.xsd
pcss-reports-models/src/main/resources/xsdSchemas/pcss-reports-models-1.xsd
pcss-reports-models/src/main/resources/xsdSchemas/pcss-reports-models-2.xsd

turn on validation

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ResourceController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/SecureEndpointController.java

Removing sensitive information from logs

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java
pcss-common-application/src/main/resources/xsdSchemas/pcss-reports.wsdl
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java

ws to common

---

pcss-common-application/src/test/java/ca/bc/gov/open/pcss/AppearanceControllerTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/CourtControllerTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ResourceControllerTests.java
pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantDeserializer.java
pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSoapConverter.java
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-3.xsd

- Fix date format on appearance

fix appearance date format

---

pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSerializer.java
pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSoapConverter.java

Fix date/timeformate cont.

---

pcss-common-application/pom.xml
pcss-common-models/pom.xml
pcss-common-secure-models/pom.xml
pcss-reports-models/pom.xml
pom.xml

- Springframework update to 2.5.8

Springframework update

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ResourceController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/SecureEndpointController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/SecureEndpointControllerTests.java

- Refactor Agen to Agency and fix one time format issue

Refactor Agen to Agency and fix one time format issue

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/SecureEndpointController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/AppearanceControllerTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ResourceControllerTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/SecureEndpointControllerTests.java
pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSerializer.java
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-3.xsd
pcss-common-secure-models/src/main/resources/xsdSchemas/pcss-common-secure-models-3.xsd

- Unit tests are also updated
- Fixed getCourtCalendarDetail and getCourtCalendarDetailSecure

Fixed date time format for getCourtCalendarDetailByDay and secure

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java
pcss-reports-models/src/main/resources/xsdSchemas/pcss-reports-models-2.xsd

Fix getJustinAdobeReport

---

pcss-common-application/src/main/resources/xsdSchemas/pcss-common-models-3v.xsd
pcss-common-application/src/main/resources/xsdSchemas/pcss-common-secure-models-3v.xsd
pcss-common-application/src/main/resources/xsdSchemas/pcss-reports-models-3v.xsd
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java
pcss-reports-models/src/main/resources/xsdSchemas/pcss-reports-models-3.xsd

Correct format

---

gitops/openshift/apps/jag-pcss-common/template/jag-pcss-common.env
gitops/openshift/apps/jag-pcss-common/template/jag-pcss-common.yaml

- Add new env fix
- Fix probe decleration

add new env

---

pcss-common-application/pom.xml
pcss-common-models/pom.xml
pcss-common-secure-models/pom.xml
pcss-reports-models/pom.xml
pom.xml

update spring framework

---

pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantDeserializer.java
pcss-common-models/src/main/java/ca/bc/gov/open/pcss/models/serializers/InstantSoapConverter.java

soap converter and deserializer fix

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/AppearanceController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/HealthController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ResourceController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/SecureEndpointController.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/models/RequestSuccessLog.java

Add success logs

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java

add upper logic in report params

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java

log clean up

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java

add jsutin reportt 2

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java

refine url parsing

---

comparison-tool/pom.xml
pcss-code-coverage/pom.xml
pcss-common-application/pom.xml
pcss-common-models/pom.xml
pcss-common-secure-models/pom.xml
pcss-reports-models/pom.xml
pom.xml

buildFrameworkFix

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ResourceController.java

fix login param names

---

pom.xml

version change

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/OrdsErrorTests.java
pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java

add oracle ords

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/configuration/SoapConfig.java
pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/ReportController.java

add ords for oracle

---

pcss-common-application/src/test/java/ca/bc/gov/open/pcss/ReportsControllerTests.java

fix test failure

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/AppearanceController.java
pcss-common-application/src/main/resources/xsdSchemas/pcss-common-secure.wsdl
pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-2.xsd

Adding SetAppearanceBail calls for setting bail fields

CCSSRED-1617

---

pcss-common-application/src/main/java/ca/bc/gov/open/pcss/controllers/CourtController.java
pcss-common-application/src/main/resources/xsdSchemas/pcss-common-secure.wsdl
pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd
pcss-common-secure-models/src/main/resources/xsdSchemas/pcss-common-secure-models-1.xsd

Updated getCourtCalendarByDay to take in application code and return bail info

CCSSRED-1616 getCourtCalendarByDay

---

pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd

Added fields to appearance to indicate if it is completed and added the court list reference number

PCSS-250 - Court Ref and Appearance

---

pcss-common-application/src/main/resources/xsdSchemas/pcss-common-secure.wsdl
pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-1.xsd
pcss-common-secure-models/src/main/resources/xsdSchemas/pcss-common-secure-models-1.xsd

Updating "BailDecisionTypeCD" to "BailDecisionTypeCd"

CCSSRED-1616 Fix

---

pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl

Completed the WSDL for bail setting

Fix setAppearanceBail

---

pcss-common-application/src/main/resources/xsdSchemas/pcss-common-secure.wsdl
pcss-common-application/src/main/resources/xsdSchemas/pcss-common.wsdl
pcss-common-models/src/main/resources/xsdSchemas/pcss-common-models-3.xsd
pcss-common-secure-models/src/main/resources/xsdSchemas/pcss-common-secure-models-3.xsd

Added "COMP" and "ADJR" to the allowed status types

New Appearance Status Types
